apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pyms-app.fullname" . }}
  labels:
    {{- include "pyms-app.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.configMap.configValue | toJson | quote }}