apiVersion: v1
kind: ConfigMap
metadata:
  name: pyms-configmap
data:
  # When the config map is mounted as a volume, these will be created as files.
  config.yaml: |-
    pyms:
      services:
        metrics: true
        swagger:
          path: "project/swagger"
          file: "swagger.yaml"
          url: "/ui/"
          project_dir: "project.views"
      config:
        DEBUG: false
        TESTING: false
        APP_NAME: pyms-app
        APPLICATION_ROOT : /
        SQLALCHEMY_TRACK_MODIFICATIONS: true
        SECRET_KEY: "gjr39dkjn344_!67#"
        DATABASE: db.sqlite3
        SQLALCHEMY_DATABASE_URI: sqlite:///db.sqlite3