kind: Service
apiVersion: v1
metadata:
  name: pyms-scaffold-v1-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: scaffold-v1
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    name: http-web